# Generated by Django 5.2.6 on 2026-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
